# Generated by Django 6.0.7 on 2026-07-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usertable_options_alter_usertable_managers_and_more'),
        ('canadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='canadmin.institutemodel'),
        ),
    ]
