# Generated by Django 6.0.7 on 2026-07-10 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidateprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter A Valid 10-Digit Mobile Number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
