# Generated by Django 6.0.7 on 2026-07-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_education_unique_user_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
