# Generated by Django 6.0.7 on 2026-07-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_alter_candidateprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
