# Generated by Django 6.0.7 on 2026-09-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_education_degree_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='field_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='institute_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='marks_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='name_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='ocr_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='ocr_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='verification_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('manual_review', 'Manual Review')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='year_verified',
            field=models.BooleanField(default=False),
        ),
    ]
