# Generated by Django 6.0.7 on 2026-09-01 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_education_degree_verified_education_field_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='education',
            name='unique_user_institute',
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.UniqueConstraint(fields=('user', 'institute', 'degree'), name='unique_user_institute_degree'),
        ),
    ]
