# Generated by Django 6.0.7 on 2026-09-02 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_remove_education_unique_user_institute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='education',
            name='unique_user_institute_degree',
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.UniqueConstraint(fields=('user', 'institute'), name='unique_user_institute'),
        ),
        migrations.RemoveField(
            model_name='education',
            name='degree_verified',
        ),
        migrations.RemoveField(
            model_name='education',
            name='field_verified',
        ),
        migrations.RemoveField(
            model_name='education',
            name='institute_verified',
        ),
        migrations.RemoveField(
            model_name='education',
            name='marks_verified',
        ),
        migrations.RemoveField(
            model_name='education',
            name='name_verified',
        ),
        migrations.RemoveField(
            model_name='education',
            name='ocr_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='ocr_raw_text',
        ),
        migrations.RemoveField(
            model_name='education',
            name='verification_message',
        ),
        migrations.RemoveField(
            model_name='education',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='education',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='education',
            name='year_verified',
        ),
    ]
