# Generated by Django 6.0.7 on 2026-09-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_remove_education_unique_user_institute_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending_review', 'Pending Manual Review'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
    ]
