# Generated by Django 6.0.7 on 2026-07-16 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ctc', models.CharField(max_length=20)),
                ('job_location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('drive_date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drives', to='canadmin.institutemodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_type', models.CharField(choices=[('aptitude', 'Aptitude'), ('coding', 'Coding'), ('gd', 'Group Discussion'), ('technical', 'Technical Interview'), ('hr', 'HR Interview')], max_length=50)),
                ('round_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='canadmin.drivemodel')),
            ],
            options={
                'ordering': ['round_order'],
            },
        ),
        migrations.CreateModel(
            name='CodingModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_statement', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50)),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('constraints', models.TextField()),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='canadmin.roundmodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AptitudeQuestionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4')], max_length=10)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_questions', to='canadmin.roundmodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='roundmodel',
            constraint=models.UniqueConstraint(fields=('drive', 'round_order'), name='unique_round_order_per_drive'),
        ),
        migrations.AddConstraint(
            model_name='roundmodel',
            constraint=models.UniqueConstraint(fields=('drive', 'round_type'), name='unique_round_type_per_drive'),
        ),
    ]
