# Generated by Django 6.0.7 on 2026-07-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0002_drivemodel_roundmodel_codingmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodingModel',
            new_name='CodingQuestionModel',
        ),
    ]
