# Generated by Django 6.0.7 on 2026-07-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0003_rename_codingmodel_codingquestionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutemodel',
            name='tpo_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institutemodel',
            name='tpo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
