# Generated by Django 6.0.7 on 2026-07-25 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0004_institutemodel_tpo_email_institutemodel_tpo_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeTestAttemptModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_attempts', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_attempts', to='canadmin.roundmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AptitudeAnswerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_option', models.CharField(blank=True, choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4')], max_length=10, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_obtained', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canadmin.aptitudequestionmodel')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='canadmin.aptitudetestattemptmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='aptitudetestattemptmodel',
            constraint=models.UniqueConstraint(fields=('candidate', 'round'), name='unique_candidate_aptitude_attempt'),
        ),
    ]
