# Generated by Django 6.0.7 on 2026-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0005_aptitudetestattemptmodel_aptitudeanswermodel_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aptitudeanswermodel',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_answer'),
        ),
    ]
