# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0006_aptitudeanswermodel_unique_attempt_question_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundAttemptModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('evaluated', 'Evaluated'), ('passed', 'Passed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='aptitudetestattemptmodel',
            name='unique_candidate_aptitude_attempt',
        ),
        migrations.AddField(
            model_name='roundattemptmodel',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roundattemptmodel',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_attempts', to='canadmin.roundmodel'),
        ),
        migrations.AlterField(
            model_name='aptitudeanswermodel',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='canadmin.roundattemptmodel'),
        ),
        migrations.RemoveField(
            model_name='aptitudetestattemptmodel',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='aptitudetestattemptmodel',
            name='round',
        ),
        migrations.AddConstraint(
            model_name='roundattemptmodel',
            constraint=models.UniqueConstraint(fields=('candidate', 'round'), name='unique_candidate_aptitude_attempt'),
        ),
        migrations.DeleteModel(
            name='AptitudeTestAttemptModel',
        ),
    ]
