# Generated by Django 6.0.7 on 2026-07-29 12:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0007_roundattemptmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roundmodel',
            name='round_start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 29, 12, 0, 23, 727257, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roundattemptmodel',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
