# Generated by Django 6.0.7 on 2026-07-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0008_roundmodel_round_start_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
