# Generated by Django 6.0.7 on 2026-07-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0009_alter_roundmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestionmodel',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='codingquestionmodel',
            name='sample_output',
        ),
        migrations.AddField(
            model_name='codingquestionmodel',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codingquestionmodel',
            name='marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='CodingTestCaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_sample', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='canadmin.codingquestionmodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmissionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('javascript', 'JavaScript')], max_length=20)),
                ('code', models.TextField(blank=True)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to='canadmin.roundattemptmodel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canadmin.codingquestionmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_submission')],
            },
        ),
    ]
