# Generated by Django 6.0.7 on 2026-07-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0010_remove_codingquestionmodel_sample_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingtestcasemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
