# Generated by Django 6.0.7 on 2026-08-01 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0011_codingtestcasemodel_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codingsubmissionmodel',
            options={'ordering': ['question_id']},
        ),
        migrations.RemoveConstraint(
            model_name='roundattemptmodel',
            name='unique_candidate_aptitude_attempt',
        ),
        migrations.AddField(
            model_name='codingsubmissionmodel',
            name='saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='codingsubmissionmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='codingsubmissionmodel',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roundattemptmodel',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='canadmin.roundmodel'),
        ),
        migrations.AddConstraint(
            model_name='roundattemptmodel',
            constraint=models.UniqueConstraint(fields=('candidate', 'round'), name='unique_candidate_round_attempt'),
        ),
    ]
