# Generated by Django 6.0.7 on 2026-08-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0012_alter_codingsubmissionmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestionSubmissionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('javascript', 'JavaScript')], max_length=20)),
                ('code', models.TextField()),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('submitted', 'Submitted')], default='saved', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='codingsubmissionmodel',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='codingsubmissionmodel',
            name='unique_attempt_question_submission',
        ),
        migrations.RenameField(
            model_name='codingsubmissionmodel',
            old_name='passed_test_cases',
            new_name='attempted_questions',
        ),
        migrations.RenameField(
            model_name='codingsubmissionmodel',
            old_name='total_test_cases',
            new_name='total_marks',
        ),
        migrations.AddField(
            model_name='codingsubmissionmodel',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingsubmissionmodel',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codingsubmissionmodel',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submission', to='canadmin.roundattemptmodel'),
        ),
        migrations.AlterField(
            model_name='codingsubmissionmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='codingquestionsubmissionmodel',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_question_submissions', to='canadmin.roundattemptmodel'),
        ),
        migrations.AddField(
            model_name='codingquestionsubmissionmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_submissions', to='canadmin.codingquestionmodel'),
        ),
        migrations.RemoveField(
            model_name='codingsubmissionmodel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='codingsubmissionmodel',
            name='language',
        ),
        migrations.RemoveField(
            model_name='codingsubmissionmodel',
            name='question',
        ),
        migrations.RemoveField(
            model_name='codingsubmissionmodel',
            name='saved_at',
        ),
        migrations.AddConstraint(
            model_name='codingquestionsubmissionmodel',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_candidate_question_submission'),
        ),
    ]
