# Generated by Django 6.0.7 on 2026-08-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0013_codingquestionsubmissionmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundattemptmodel',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.CreateModel(
            name='RoundCandidateDecisionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_decision', to='canadmin.roundattemptmodel')),
                ('next_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_candidates', to='canadmin.roundmodel')),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
    ]
