# Generated by Django 6.0.7 on 2026-08-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadmin', '0014_alter_roundattemptmodel_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundmodel',
            old_name='duration_minutes',
            new_name='test_duration_minutes',
        ),
        migrations.AddField(
            model_name='roundmodel',
            name='is_test_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roundmodel',
            name='round_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
