# Generated by Django 6.0.7 on 2026-09-21 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "canadmin",
            "0015_rename_duration_minutes_roundmodel_test_duration_minutes_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveCandidateModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drives_assigned_by_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_drives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_candidates",
                        to="canadmin.drivemodel",
                    ),
                ),
            ],
            options={
                "ordering": ["assigned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("drive", "candidate"),
                        name="unique_drive_candidate_assignment",
                    )
                ],
            },
        ),
    ]
